export const TEAMS = [
  {id:'rsa',name:'África do Sul',flag:'🇿🇦'},
  {id:'ger',name:'Alemanha',flag:'🇩🇪'},
  {id:'ksa',name:'Arábia Saudita',flag:'🇸🇦'},
  {id:'alg',name:'Argélia',flag:'🇩🇿'},
  {id:'arg',name:'Argentina',flag:'🇦🇷'},
  {id:'aus',name:'Austrália',flag:'🇦🇺'},
  {id:'aut',name:'Áustria',flag:'🇦🇹'},
  {id:'bel',name:'Bélgica',flag:'🇧🇪'},
  {id:'bih',name:'Bósnia e Herzegovina',flag:'🇧🇦'},
  {id:'bra',name:'Brasil',flag:'🇧🇷'},
  {id:'cpv',name:'Cabo Verde',flag:'🇨🇻'},
  {id:'can',name:'Canadá',flag:'🇨🇦'},
  {id:'qat',name:'Catar',flag:'🇶🇦'},
  {id:'col',name:'Colômbia',flag:'🇨🇴'},
  {id:'kor',name:'Coreia do Sul',flag:'🇰🇷'},
  {id:'civ',name:'Costa do Marfim',flag:'🇨🇮'},
  {id:'cro',name:'Croácia',flag:'🇭🇷'},
  {id:'crc',name:'Curaçao',flag:'🇨🇼'},
  {id:'egy',name:'Egito',flag:'🇪🇬'},
  {id:'ecu',name:'Equador',flag:'🇪🇨'},
  {id:'sco',name:'Escócia',flag:'🏴'},
  {id:'esp',name:'Espanha',flag:'🇪🇸'},
  {id:'usa',name:'Estados Unidos',flag:'🇺🇸'},
  {id:'fra',name:'França',flag:'🇫🇷'},
  {id:'gha',name:'Gana',flag:'🇬🇭'},
  {id:'hai',name:'Haiti',flag:'🇭🇹'},
  {id:'ned',name:'Holanda',flag:'🇳🇱'},
  {id:'eng',name:'Inglaterra',flag:'🏴'},
  {id:'irn',name:'Irã',flag:'🇮🇷'},
  {id:'irq',name:'Iraque',flag:'🇮🇶'},
  {id:'jpn',name:'Japão',flag:'🇯🇵'},
  {id:'jor',name:'Jordânia',flag:'🇯🇴'},
  {id:'mar',name:'Marrocos',flag:'🇲🇦'},
  {id:'mex',name:'México',flag:'🇲🇽'},
  {id:'nor',name:'Noruega',flag:'🇳🇴'},
  {id:'nzl',name:'Nova Zelândia',flag:'🇳🇿'},
  {id:'pan',name:'Panamá',flag:'🇵🇦'},
  {id:'par',name:'Paraguai',flag:'🇵🇾'},
  {id:'por',name:'Portugal',flag:'🇵🇹'},
  {id:'cod',name:'RD Congo',flag:'🇨🇩'},
  {id:'sen',name:'Senegal',flag:'🇸🇳'},
  {id:'swe',name:'Suécia',flag:'🇸🇪'},
  {id:'sui',name:'Suíça',flag:'🇨🇭'},
  {id:'cze',name:'Tchéquia',flag:'🇨🇿'},
  {id:'tun',name:'Tunísia',flag:'🇹🇳'},
  {id:'tur',name:'Turquia',flag:'🇹🇷'},
  {id:'uru',name:'Uruguai',flag:'🇺🇾'},
  {id:'uzb',name:'Uzbequistão',flag:'🇺🇿'}
];

export const TEAM_IDS = TEAMS.map(t => t.id);

export function teamName(id) {
  return TEAMS.find(t => t.id === id)?.name || id;
}
